[build]
  publish = "client/build"
  command = "npm run install-all && cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://votre-api-vercel.vercel.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://votre-api-vercel.vercel.app/api"
  REACT_APP_SOCKET_URL = "https://votre-api-vercel.vercel.app"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://votre-api-vercel.vercel.app/api"
  REACT_APP_SOCKET_URL = "https://votre-api-vercel.vercel.app"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://votre-api-vercel.vercel.app/api"
  REACT_APP_SOCKET_URL = "https://votre-api-vercel.vercel.app" 